name = "pygamer_bsp"
version = "1.0.0"

description = "Board Support Package for the AdaFruit PyGamer"
licenses = "BSD-3-Clause"
maintainers = ["fabien.chouteau@gmail.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["pygamer_bsp.gpr"]
tags = ["embedded", "nostd", "pygamer", "adafruit", "game", "console", "bsp"]

[configuration]
disabled = true

[[depends-on]]
cortex_m = "~0.1.0"
samd51_hal = "~0.3.0"
